"""
Auto-generated heuristic for kernel: scaled_mm
Backend: decision_tree

Provides:
- key_scaled_mm(*args): Returns config index (cache key)
- autotune_scaled_mm(*args): Returns config dict for the given arguments

Pretuned on NVIDIA H100 (sm90) for FP8 scaled matmul across the
(K, N) weight shapes and small token counts (M) used by vLLM serving.
Config selection mirrors the vLLM pick_config strategy: closest K,
then closest N, then the smallest tuned M >= the input M (falling back
to the largest tuned M).
"""

import functools

# Tuned (K, N, M) keys, parallel to the config list in autotune_scaled_mm.
_KEYS = [
    (2048, 4096, 1),
    (2048, 2048, 1),
    (2048, 12288, 1),
    (6144, 2048, 1),
    (4096, 6144, 1),
    (4096, 4096, 1),
    (4096, 24576, 1),
    (12288, 4096, 1),
    (5120, 10240, 1),
    (5120, 5120, 1),
    (5120, 51200, 1),
    (25600, 5120, 1),
    (2048, 4096, 2),
    (2048, 2048, 2),
    (2048, 12288, 2),
    (6144, 2048, 2),
    (4096, 6144, 2),
    (4096, 4096, 2),
    (4096, 24576, 2),
    (12288, 4096, 2),
    (5120, 10240, 2),
    (5120, 5120, 2),
    (5120, 51200, 2),
    (25600, 5120, 2),
    (2048, 4096, 4),
    (2048, 2048, 4),
    (2048, 12288, 4),
    (6144, 2048, 4),
    (4096, 6144, 4),
    (4096, 4096, 4),
    (4096, 24576, 4),
    (12288, 4096, 4),
    (5120, 10240, 4),
    (5120, 5120, 4),
    (5120, 51200, 4),
    (25600, 5120, 4),
    (2048, 4096, 8),
    (2048, 2048, 8),
    (2048, 12288, 8),
    (6144, 2048, 8),
    (4096, 6144, 8),
    (4096, 4096, 8),
    (4096, 24576, 8),
    (12288, 4096, 8),
    (5120, 10240, 8),
    (5120, 5120, 8),
    (5120, 51200, 8),
    (25600, 5120, 8),
    (2048, 4096, 16),
    (2048, 2048, 16),
    (2048, 12288, 16),
    (6144, 2048, 16),
    (4096, 6144, 16),
    (4096, 4096, 16),
    (4096, 24576, 16),
    (12288, 4096, 16),
    (5120, 10240, 16),
    (5120, 5120, 16),
    (5120, 51200, 16),
    (25600, 5120, 16),
    (2048, 4096, 32),
    (2048, 2048, 32),
    (2048, 12288, 32),
    (6144, 2048, 32),
    (4096, 6144, 32),
    (4096, 4096, 32),
    (4096, 24576, 32),
    (12288, 4096, 32),
    (5120, 10240, 32),
    (5120, 5120, 32),
    (5120, 51200, 32),
    (25600, 5120, 32),
    (2048, 4096, 64),
    (2048, 2048, 64),
    (2048, 12288, 64),
    (6144, 2048, 64),
    (4096, 6144, 64),
    (4096, 4096, 64),
    (4096, 24576, 64),
    (12288, 4096, 64),
    (5120, 10240, 64),
    (5120, 5120, 64),
    (5120, 51200, 64),
    (25600, 5120, 64),
    (2048, 4096, 128),
    (2048, 2048, 128),
    (2048, 12288, 128),
    (6144, 2048, 128),
    (4096, 6144, 128),
    (4096, 4096, 128),
    (4096, 24576, 128),
    (12288, 4096, 128),
    (5120, 10240, 128),
    (5120, 5120, 128),
    (5120, 51200, 128),
    (25600, 5120, 128),
]


# Built once at import (not per call): K -> N -> sorted tuned-M list and an
# O(1) (K, N, M) -> config-index map.
_CONFIGS_BY_KN: dict[int, dict[int, list[int]]] = {}
for _kk, _nn, _mm in _KEYS:
    _CONFIGS_BY_KN.setdefault(_kk, {}).setdefault(_nn, []).append(_mm)
for _by_n in _CONFIGS_BY_KN.values():
    for _ms in _by_n.values():
        _ms.sort()
_INDEX_BY_KNM: dict[tuple[int, int, int], int] = {
    key: i for i, key in enumerate(_KEYS)
}


@functools.cache
def _pick_index(M: int, K: int, N: int) -> int:
    # Fast path: exact tuned shape -> use its config directly.
    exact = _INDEX_BY_KNM.get((K, N, M))
    if exact is not None:
        return exact
    # Otherwise nearest-neighbor:
    # 1. closest K, 2. closest N, 3. smallest tuned M >= M (else largest).
    best_K = min(_CONFIGS_BY_KN, key=lambda s: abs(s - K))
    best_N = min(_CONFIGS_BY_KN[best_K], key=lambda s: abs(s - N))
    available_M = _CONFIGS_BY_KN[best_K][best_N]
    best_M = next((m for m in available_M if m >= M), available_M[-1])
    return _INDEX_BY_KNM[(best_K, best_N, best_M)]


def key_scaled_mm(*args) -> int:
    """Select config index for the given arguments (also serves as cache key).

    key_scaled_mm is on the per-call specialization-key path
    (helion/runtime/kernel.py _base_specialization_key), so the pick is
    memoized on the (M, K, N) ints via functools.cache to stay O(1) per call.
    The kernel args (tensors) are not cached directly -- that would never hit
    (new tensors each call) and would pin GPU memory.
    """
    # args = (c, a, b, scale_a, scale_b, bias); a is [M, K], b is [K, N].
    a = args[1]
    b = args[2]
    return _pick_index(int(a.shape[0]), int(a.shape[1]), int(b.shape[1]))


def autotune_scaled_mm(*args) -> dict:
    """Select the optimal config for the given arguments."""
    _C = [
        {'block_sizes': [1, 8, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [4, 4], 'range_warp_specializes': [], 'range_multi_buffers': [True, None], 'range_flattens': [False, None], 'load_eviction_policies': ['first', 'last', 'first', '', 'last', '', 'first'], 'num_warps': 1, 'num_stages': 8, 'indexing': ['tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'atomic_indexing': [], 'pid_type': 'persistent_blocked', 'num_sm_multiplier': 4, 'maxnreg': 128},
        {'block_sizes': [1, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'last', 'first', '', '', 'last', ''], 'num_warps': 2, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'persistent_blocked', 'num_sm_multiplier': 8, 'maxnreg': 128},
        {'block_sizes': [1, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [16], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'last', 'last', 'last', 'last', '', ''], 'num_warps': 2, 'num_stages': 3, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [1, 16, 512], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [4, 0], 'range_warp_specializes': [], 'range_multi_buffers': [True, True], 'range_flattens': [False, False], 'load_eviction_policies': ['first', 'last', 'first', 'last', '', 'first', 'first'], 'num_warps': 2, 'num_stages': 4, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'atomic_indexing': [], 'pid_type': 'persistent_interleaved', 'num_sm_multiplier': 4, 'maxnreg': 256},
        {'block_sizes': [1, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['first', 'last', 'last', '', 'first', 'first', 'last'], 'num_warps': 1, 'num_stages': 5, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [1, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [4, 4], 'range_warp_specializes': [], 'range_multi_buffers': [True, None], 'range_flattens': [True, True], 'load_eviction_policies': ['', 'last', 'first', '', '', '', 'first'], 'num_warps': 2, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'persistent_interleaved', 'num_sm_multiplier': 2, 'maxnreg': 128},
        {'block_sizes': [1, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', 'last', 'first', 'last', '', 'first', 'last'], 'num_warps': 1, 'num_stages': 3, 'indexing': ['tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [1, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', '', 'first', 'first', 'last', 'last', 'first'], 'num_warps': 2, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [2, 16, 512], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'first', 'last', 'first', 'first', '', 'last'], 'num_warps': 2, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [4, 16, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'last', 'last', '', 'last', 'last', ''], 'num_warps': 1, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [16, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['', '', '', '', 'first', 'last', ''], 'num_warps': 2, 'num_stages': 2, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [1, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['first', 'first', '', 'last', 'last', 'last', 'first'], 'num_warps': 1, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['last', '', 'first', 'last', 'last', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [2, 16, 512], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'last', 'last', 'first', 'last', '', 'last'], 'num_warps': 4, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [2, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [4], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, False], 'load_eviction_policies': ['', 'first', '', 'last', 'last', 'last', ''], 'num_warps': 2, 'num_stages': 3, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [2, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'first', '', 'first', 'first', 'first', ''], 'num_warps': 1, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['last', '', 'first', 'last', 'last', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [2, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', 'first', '', 'first', 'first', 'first', ''], 'num_warps': 2, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [2, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['', '', 'first', '', 'last', '', ''], 'num_warps': 2, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [2, 16, 512], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'first', 'last', 'first', 'first', '', 'last'], 'num_warps': 2, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [8, 16, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'last', 'first', 'last', '', 'last', ''], 'num_warps': 1, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [2, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['last', '', 'first', 'first', '', '', 'last'], 'num_warps': 2, 'num_stages': 2, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'first', 'last', 'first', 'first', 'last', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['last', '', 'first', 'last', 'last', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [4, 16, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['first', '', 'first', 'last', '', '', 'last'], 'num_warps': 2, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [4, 16, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'last', 'last', '', 'last', 'last', ''], 'num_warps': 1, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [8, 32, 512], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', '', 'last', 'last', '', 'first', ''], 'num_warps': 4, 'num_stages': 4, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [4, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', '', 'last', '', ''], 'num_warps': 4, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [4, 32, 512], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['first', 'last', 'first', '', '', 'last', ''], 'num_warps': 4, 'num_stages': 5, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [4, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, True], 'load_eviction_policies': ['', '', 'last', '', 'first', 'first', 'first'], 'num_warps': 2, 'num_stages': 4, 'indexing': ['tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [4, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [4], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', '', 'last', '', 'last', 'first', 'first'], 'num_warps': 1, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [4, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'last', 'last', '', '', '', 'last'], 'num_warps': 2, 'num_stages': 2, 'indexing': ['tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [4, 32, 1024], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'first', 'first', '', '', '', 'last'], 'num_warps': 2, 'num_stages': 3, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [8, 16, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, False], 'load_eviction_policies': ['first', 'last', 'first', 'first', 'last', 'first', 'last'], 'num_warps': 2, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [8, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['', '', '', '', 'last', 'last', ''], 'num_warps': 2, 'num_stages': 3, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [8, 16, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'last', 'first', 'last', '', 'last', ''], 'num_warps': 1, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [8, 32, 512], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', '', 'last', 'last', '', 'first', ''], 'num_warps': 4, 'num_stages': 4, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [16, 64, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['', 'first', 'first', 'first', 'last', 'first', 'first'], 'num_warps': 4, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [8, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['first', '', 'last', '', '', '', ''], 'num_warps': 2, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [8, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [4], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['first', '', 'first', 'last', 'last', '', ''], 'num_warps': 2, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [8, 16, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'last', 'first', 'last', '', 'last', ''], 'num_warps': 1, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [8, 64, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [32], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'last', 'first', 'last', 'last', 'last', ''], 'num_warps': 8, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [8, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['first', 'first', 'first', 'first', '', 'first', 'first'], 'num_warps': 2, 'num_stages': 7, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'xyz'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', '', 'first', '', '', 'first', 'last'], 'num_warps': 4, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [16, 32, 128], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', 'first', 'last', 'first', '', 'first', ''], 'num_warps': 4, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'first', 'first', 'first', '', 'last', 'first'], 'num_warps': 4, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', '', 'first', '', '', 'first', 'last'], 'num_warps': 4, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [16, 64, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['', 'first', 'first', 'first', 'last', 'first', 'first'], 'num_warps': 4, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', '', 'first', '', '', 'first', 'last'], 'num_warps': 4, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [16, 16, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [32], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['first', '', 'first', 'first', 'first', 'last', 'first'], 'num_warps': 2, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'first', 'last', 'first', 'first', 'last', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [16, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['', '', '', '', 'first', 'last', ''], 'num_warps': 2, 'num_stages': 2, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'first', 'last', 'first', 'first', 'last', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, False], 'load_eviction_policies': ['', '', 'first', 'last', '', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 128, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['last', '', '', 'last', 'last', 'first', 'last'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'first', 'first', 'first', '', 'last', 'first'], 'num_warps': 4, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', '', 'first', '', '', 'first', 'last'], 'num_warps': 4, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [32, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [4], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['first', 'last', 'first', 'last', '', '', 'first'], 'num_warps': 2, 'num_stages': 3, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['', '', 'first', '', '', 'first', 'last'], 'num_warps': 4, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 128, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['first', 'last', '', 'first', '', 'last', 'last'], 'num_warps': 8, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'first', 'last', 'first', 'first', 'last', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [32, 128, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'last', 'first', 'last', '', 'last', 'last'], 'num_warps': 2, 'num_stages': 2, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [32, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [1, 1], 'range_warp_specializes': [], 'range_multi_buffers': [False, None], 'range_flattens': [False, True], 'load_eviction_policies': ['', '', 'last', 'last', '', 'last', 'last'], 'num_warps': 2, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'persistent_blocked', 'num_sm_multiplier': 4, 'maxnreg': 256},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [64], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, False], 'load_eviction_policies': ['last', '', 'first', 'last', 'last', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 128, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['first', 'last', '', 'first', '', 'last', 'last'], 'num_warps': 8, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 16, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, False], 'load_eviction_policies': ['last', 'first', 'first', 'last', 'last', '', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'first', '', '', 'last', 'first', 'first'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', '', 'last', 'first', 'first', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['first', 'first', 'last', '', 'first', 'last', 'last'], 'num_warps': 4, 'num_stages': 3, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', '', 'last', 'first', 'first', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 128, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['first', 'last', '', 'first', '', 'last', 'last'], 'num_warps': 8, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, True], 'load_eviction_policies': ['last', 'first', 'first', 'first', '', 'last', 'first'], 'num_warps': 4, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'first', '', '', 'last', 'first', 'first'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[1, 0]], 'l2_groupings': [1], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'first', '', '', 'last', 'first', 'first'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'first', 'last', 'first', 'first', 'last', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [2], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, False], 'load_eviction_policies': ['', '', 'first', 'last', '', 'first', 'last'], 'num_warps': 4, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'last', 'last', 'first', 'last', '', ''], 'num_warps': 4, 'num_stages': 4, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 32, 256], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, False], 'load_eviction_policies': ['first', 'first', 'last', 'first', '', 'first', 'first'], 'num_warps': 4, 'num_stages': 7, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 128, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [64], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['last', '', '', 'last', 'last', 'first', 'last'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['first', '', 'first', 'first', 'last', '', ''], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 128, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [8], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['last', '', '', 'first', 'last', 'last', 'first'], 'num_warps': 8, 'num_stages': 3, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 64, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [1], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['first', 'last', 'last', 'last', '', 'last', 'last'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [128, 128, 128], 'loop_orders': [[1, 0]], 'l2_groupings': [16], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['first', 'last', '', 'first', 'last', 'first', 'first'], 'num_warps': 8, 'num_stages': 6, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [64, 128, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'last', 'first', 'last', '', 'first', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [128, 128, 128], 'loop_orders': [[1, 0]], 'l2_groupings': [32], 'range_unroll_factors': [0, 2], 'range_warp_specializes': [], 'range_multi_buffers': [True, None], 'range_flattens': [False, True], 'load_eviction_policies': ['last', 'first', '', 'last', 'first', 'first', 'first'], 'num_warps': 8, 'num_stages': 3, 'indexing': ['pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'persistent_blocked', 'num_sm_multiplier': 2, 'maxnreg': 128},
        {'block_sizes': [128, 64, 128], 'loop_orders': [[0, 1]], 'l2_groupings': [16], 'range_unroll_factors': [0, 1], 'range_warp_specializes': [], 'range_num_stages': [], 'range_multi_buffers': [None, True], 'range_flattens': [None, None], 'load_eviction_policies': ['last', '', '', '', 'last', 'last', 'first'], 'num_warps': 4, 'num_stages': 8, 'indexing': ['tensor_descriptor', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'tensor_descriptor', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
    ]
    return _C[key_scaled_mm(*args)]
